---
title: "Pop Estimates"
author: "Kyle Belanger"
date: "3/12/2020"
output: html_document
runtime: shiny
---
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  # knitr::opts_knit$set(root.dir='../../')
  
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 4, 
  fig.width = 5.5, 
  out.width = "550px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 400
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("../../analysis/population-estimates/population-estimates-shiny.R")
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load-packages, echo=echoChunks, message=FALSE}
```


<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load-sources, echo=echoChunks, message=FALSE}
```


<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare-globals, echo=echoChunks, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=echoChunks, message=FALSE}
#Put code in here.  It doesn't call a chunk in the codebehind file.
```
# Load Data

<!-- Load the datasets.   -->
```{r load-data, echo=echoChunks, results='show', message=FALSE}
```

<!-- Inspect the datasets.   -->
```{r inspect-data, echo=echoChunks, results='show', message=FALSE}
```

# Tweak Data

<!-- Tweak the datasets.   -->
```{r tweak-data, echo=echoChunks, results='show', message=FALSE}
```



<!-- Basic table view.   -->
```{r basic-table, echo=TRUE, results='show', message=FALSE}
```

<!-- G1   -->

# Graph 1 

```{r g1, echo=TRUE, results='show', message=FALSE}
```


<!-- G2 -->
```{r g2, echo = TRUE, results='show'}

```

<!-- G3 -->
```{r g3, echo = TRUE, results='show'}

```

