---
title: "Youth Suicide in Florida"
author: "Andriy Koval"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: simplex
    toc: true
    toc_depth: 3
    keep_md: true
    toc_float: true
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 8, 
  fig.width = 9, 
  out.width = "700px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 400
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script
read_chunk("./analysis/tallahassee/age12_18/tallahassee-age12_18.R")
# read_chunk("../../../analysis/talahassee/age12_18/talahassee-age12_18.R")
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load-packages, echo=echoChunks, message=FALSE}
```

<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load-sources, echo=echoChunks, message=FALSE}
```


# I. Exposition

## Glossary
Review object definitions to assist you in reading the report. 
<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare-globals, echo=T, results='show', message=FALSE, warning=F}
color_race
```

Review functions definitions to assist you in reading the report.
```{r utility-functions, echo=echoChunks, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=echoChunks, message=FALSE}
#Put code in here.  It doesn't call a chunk in the codebehind file.
```

## Load Data
<!-- Load the datasets.   -->
```{r load-data, echo=TRUE, results='hide', message=FALSE}
```

<!-- Inspect the datasets.   -->
```{r inspect-data, echo=echoChunks, results='hide', message=FALSE}
```

## Data Tweaks
<!-- Tweak the datasets.   -->
```{r tweak-data, echo=T, results='hide', message=FALSE, warning=F}
```


```{r basic-graph}

```



```{r dev-a-0, echo=T, results='asos', message=FALSE}
ds_sex_cause %>% glimpse()
```

# II. Without Race

## A1 - Sex-Cause
```{r allrace-sex-cause, echo=T, message=FALSE, results='show'}
g1 <- ds_sex %>% 
  ggplot(aes(x = year, y = value, color = sex) )+
  geom_point()+
  geom_line(aes(group=sex))+
  facet_grid(measure ~ mortality_cause, scales = "free")+
  theme_bw()+
  labs(
    title = "Gender differences within each mortality cause"
  )
g1 %>% print()

```

## A2 - Cause-Sex
```{r allrace-cause-sex, echo=T, results='show', message=FALSE}
g2 <- ds_sex %>% 
  ggplot(aes(x = year, y = value, color = mortality_cause) )+
  geom_point()+
  geom_line(aes(group=mortality_cause))+
  facet_grid(measure ~ sex, scales = "free")+
  theme_bw()+
  labs(
    title = "Mortality cause within each gender"
  )

g2%>% print()
```



# III. With Race

## B1 - Race-Sex-Cause
```{r race-sex-cause, echo=T, results='show', message=FALSE}

for(i in names(color_race) ){
  g1 <- ds_sex_race %>%
    dplyr::filter(race == i) %>%
    ggplot(aes(x = year, y = value, color = sex) )+
    geom_point()+
    geom_line(aes(group=sex))+
    facet_grid(measure ~ mortality_cause, scales = "free")+
    theme_bw()+
    labs(
      title = paste0(toupper(i),": Gender differences within each mortality cause")
    )
  g1 %>% print()

}

```

## B2 - Race-Cause-Sex
```{r race-cause-sex, echo=F, results='show', message=FALSE}
for(i in names(color_race) ){
g1 <- ds_sex_race %>% 
  dplyr::filter(race == i) %>% 
  ggplot(aes(x = year, y = value, color = mortality_cause) )+
  geom_point()+
  geom_line(aes(group=mortality_cause))+
  facet_grid(measure ~ sex, scales = "free")+
  theme_bw()+
  labs(
    title = paste0(toupper(i),": Mortality cause within each gender")
  )
g1 %>% print()
}
```


## C1 - Sex-Cause-Race
```{r sex-cause-race, echo=T, results='show', message=FALSE}
for(i in names(color_sex) ){
  g1 <- ds_sex_race %>% 
    dplyr::filter(sex == i) %>% 
    ggplot(aes(x = year, y = value, color = mortality_cause) )+
    geom_point()+
    geom_line(aes(group=mortality_cause))+
    facet_grid(measure ~ race, scales = "free")+
    theme_bw()+
    labs(
      title =  paste0("Sex = ",toupper(i),": Mortality causes for each race")
    )
  g1 %>% print()
}
```

## C2 - Sex-Race-Cause
```{r sex-race-cause, echo=T, results='show', message=FALSE}
for(i in names(color_sex) ){
  g1 <- ds_sex_race %>% 
    dplyr::filter(sex == i) %>% 
    ggplot(aes(x = year, y = value, color = race) )+
    geom_point()+
    geom_line(aes(group=race))+
    facet_grid(measure ~ mortality_cause , scales = "free")+
    theme_bw()+
    labs(
      title = paste0("Sex = ",toupper(i),": Race differences for each mortality cause")
    )
  g1 %>% print()
}
```


## D1 - Cause-Sex-Race
```{r cause-sex-race, echo=T, results='show', message=FALSE}
for( i in names(color_cause) ){
  g1 <- ds_sex_race %>% 
    dplyr::filter(mortality_cause == i) %>% 
    ggplot(aes(x = year, y = value, color = sex) )+
    geom_point()+
    geom_line(aes(group=sex))+
    facet_grid(measure ~ race, scales = "free")+
    theme_bw()+
    labs(
      title = paste0("Cause = ",toupper(i),": Gender differences in each race")
    )
  g1 %>% print()
}
```

## D2 - Cause-Race-Sex
```{r cause-race-sex, echo=T, results='show', message=FALSE}
for( i in names(color_cause) ){
  g1 <- ds_sex_race %>% 
    dplyr::filter(mortality_cause == i) %>% 
    ggplot(aes(x = year, y = value, color = race) )+
    geom_point()+
    geom_line(aes(group=race))+
    facet_grid(measure ~ sex, scales = "free")+
    theme_bw()+
    labs(
      title =  paste0("Cause = ",toupper(i),": Race differences for each gender")
    )
  g1 %>% print()
}
```

# IV. Recap
```{r recap-0, echo=T, results='show', message=FALSE}
```

```{r recap-1, echo=T, results='show', message=FALSE}
```

```{r recap-2, echo=T, results='show', message=FALSE}
```

```{r recap-3, echo=T, results='show', message=FALSE}
```


```{r xxx, echo=T, results='show', message=FALSE}
```



```{r session-info, echo=FALSE}
cat("Report rendered by", Sys.info()["user"], "at", strftime(Sys.time(), "%Y-%m-%d, %H:%M %z"))
sessionInfo()
```
